services:
  - type: web
    name: dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn dashboard.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: dashboard.settings
